// author: https://github.com/AnotherGithubDude, 2022
// compiled with: rustc hello_world.rs (rustc 1.65.0)
// parts generated by:
// https://beta.openai.com/playground/p/default-chat

use std::env;
use std::fs;

fn main() {
    let args: Vec<String> = env::args().collect();

    if args.len() < 2 {
        eprintln!("please provide a folder path");
        std::process::exit(1);
    }

    let path = &args[1];

    let entries = fs::read_dir(path).unwrap();

    println!("File names in folder {}", path);

    for entry in entries {
        println!("{}", entry.unwrap().path().display());
    }
}
