# author: https://github.com/AnotherGithubDude, 2022
# tested with julia 1.8.3: $ julia files-sorted.jl
# parts generated by: 
# https://beta.openai.com/playground/p/default-chat

files = readdir()         # Reads the directory
sortedFiles = sort(files) # sorts the files alphabetically
for file in sortedFiles
    println(file)         # prints each file individually
end

