# author: https://github.com/AnotherGithubDude, 2022
# tested with julia 1.8.3: $ julia files-sorted.jl
# parts generated by: 
# https://beta.openai.com/playground/p/default-chat

starttime = time()
files = readdir() 
filenames = sort(files) #sort files alphabetically

file_open = open("folder.txt", "w") #open folder.txt for writing
for f in filenames #write the sorted file names to folder.txt
    write(file_open,f,"\n")
end
close(file_open) #close folder.txt

elapsetime = time() - starttime #calculate time taken
println("Time taken: $(elapsetime) seconds")
exit() #exit gracefully
