# author: https://github.com/AnotherGithubDude, 2022
# tested with julia 1.8.3: $ julia read-from-file.jl
# parts generated by: 
# https://beta.openai.com/playground/p/default-chat

starttime = time() # for performance measurement
try
    f = open("folder.txt") 
#    contents = readstring(f) 
    contents = read(f, String)
    println(contents) 
    close(f)
    println("Time elapsed: $(time() - starttime) seconds") 
catch err
    println("An error occured while opening or reading the file: $err")
finally
    println("done")
end
