/*
author: https://github.com/AnotherGithubDude, 2022
parts generated by: 
https://beta.openai.com/playground/p/default-chat
tested with scala: Scala 3.2.1 (19.0.1, Java OpenJDK 64-Bit Server VM)
$ scala files_of_directory_to_file.scala
*/
import java.io._

object FilesList {
  def main(args: Array[String]): Unit = {
    val dir = new File(".")
    val allFiles = dir.listFiles

    // Print all files
    println("\n=====\nList of all files in this directory:\n=====\n")
    for (file <- allFiles) {
      println(file.getName)
    }

    // Write to file 
    val fileToWrite = new FileWriter("files.txt", true)
    try {
        for (file <- allFiles) {
            fileToWrite.write(file.getName + "\n")
        }
    } finally {
        fileToWrite.close()
    }

    println("\nFile list written to 'files.txt'.")

    // Gracefully exit
    println("\nAll done! Goodbye!")
  }
}
