/*
author: https://github.com/AnotherGithubDude, 2022
parts generated by: 
https://beta.openai.com/playground/p/default-chat
tested with scala: Scala 3.2.1 (19.0.1, Java OpenJDK 64-Bit Server VM)
$ scala hello_world.scala
*/
object HelloWorld {
  def main(args: Array[String]): Unit = {
    println("Hello World!")
  }
}
