       IDENTIFICATION DIVISION. 
       PROGRAM-ID. HELLO-WORLD. 
       ENVIRONMENT DIVISION. 
       CONFIGURATION SECTION. 
       DATA DIVISION. 
       PROCEDURE DIVISION. 
           DISPLAY "Hello World.". 
           DISPLAY "Author: https://github.com/AnotherGithubDude, 2022".
           DISPLAY "Compiled with cobc (GnuCOBOL) 3.1.2.0 on Mac:".
           DISPLAY "$ cobc -x hello_world.cbl" 
           DISPLAY "Parts have been automatically generated by:".
           DISPLAY "https://beta.openai.com/playground/p/default-chat". 
           STOP RUN. 
       END PROGRAM HELLO-WORLD.
